# Generated by Django 3.2 on 2022-02-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('phoneNo', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('description', models.TextField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
